-   id: usort
    name: usort
    entry: usort
    require_serial: true
    language: python
    language_version: python3
    types_or: [cython, pyi, python]
    args: ['format']
    minimum_pre_commit_version: '2.9.2'
